services:
  - type: web
    name: amazone-api
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: STRIPE_SECRET_KEY
        value: sk_test_51Tpm802EhWO7P1YiQ13gHyjgTt0AvpjydTvwRZ8QrKKrPBT4gyv8rCl6tq7PsLxnFkJqNJPWYEt8GJLKtdr0zN4300tQUuKKKY
      - key: STRIPE_WEBHOOK_SECRET
        value: whsec_ywLFgjz0TQkXVG9WgkeB7zKGg23RP88t
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001